openapi: 3.2.0
info:
  title: Loan Import API
  version: 4.0.0
servers:
- url: https://api-test.freddiemac.com/single-family/lsa
security:
- bearerAuth: []
tags:
- name: Loan Import API
paths:
  /v1/loans/import:
    post:
      tags:
      - Loan Import API
      summary: Loan Import API
      description: 'The request metadata must be included in the ''requestMetadataJson'' field as a JSON object. Update the example JSON below to fit your scenario.


        **Example 1: Request Metadata for Seller for import and allocate an existing Loan to a Guarantor contract.**


        Please change the following fields to submit a valid request and “Try it out”


        ''sellerIdentifier'', ''sellerOrganizationBranchIdentifier'', ''investorContractIdentifier''

        ```json

        {

        "correlationIdentifier": "5234-1156-83456",

        "sellerIdentifier": "999999",

        "sellerOrganizationBranchIdentifier": 999999,

        "counterPartyType": "Seller",

        "overwriteExistingLoan": true,

        "contractUPBLimitIndicator": false,

        "useSellerLoanIdOnly": false,

        "requestToEvaluateLoans": false,

        "investorContractIdentifier": 99999999

        }

        ```


        **Example 2: Request Metadata for Seller for import, allocate and evaluate New Cash loan providing Contract number_in the file.**


        Please change the following fields to submit a valid request and “Try it out”


        ''sellerIdentifier'', ''sellerOrganizationBranchIdentifier'', ''pricingIdentifier''

        ```json

        {

        "correlationIdentifier": "1234-1126-83456",

        "sellerIdentifier": "999999",

        "sellerOrganizationBranchIdentifier": 999999,

        "counterPartyType": "Seller",

        "overwriteExistingLoan": false,

        "contractUPBLimitIndicator": true,

        "useSellerLoanIdOnly": false,

        "pricingIdentifier": "M99999999"

        }

        ```


        **Example 3: Request Metadata for Seller for import, allocate and evaluate new Cash Loan.**


        Please change the following fields to submit a valid request and “Try it out”


        ''sellerIdentifier'', ''sellerOrganizationBranchIdentifier'', ''investorContractIdentifier''

        ```json

        {

        "correlationIdentifier": "3234-1126-81456",

        "sellerIdentifier": "999999",

        "sellerOrganizationBranchIdentifier": 999999,

        "counterPartyType": "Seller",

        "overwriteExistingLoan": false,

        "contractUPBLimitIndicator": true,

        "useSellerLoanIdOnly": false,

        "investorContractIdentifier": 99999999

        }

        ```


        **Example 4: Request Metadata For Seller for Import and evaluate New_Unallocated Loan.**


        Please change the following fields to submit a valid request and “Try it out”


        ''sellerIdentifier'', ''sellerOrganizationBranchIdentifier''

        ```json

        {

        "correlationIdentifier": "7234-1156-53456",

        "sellerIdentifier": "999999",

        "sellerOrganizationBranchIdentifier": 999999,

        "counterPartyType": "Seller",

        "overwriteExistingLoan": false,

        "contractUPBLimitIndicator": false,

        "useSellerLoanIdOnly": false

        }

        ```


        **Example 5: Request Metadata for Secondary Market Advisor [SMA] for Import, allocate and evaluate New loan to a Guarantor contract providing a Pool number in the request metadata.**


        Please change the following fields to submit a valid request and “Try it out”


        ''sellerIdentifier'', ''sellerOrganizationBranchIdentifier'',''requestingPartyAccountIdentifier'', ''pricingIdentifier'', ''poolNumber''

        ```json

        {

        "correlationIdentifier": "9234-1196-53486",

        "sellerIdentifier": "999999",

        "sellerOrganizationBranchIdentifier": 999999,

        "requestingPartyAccountIdentifier": "SMA999",

        "counterPartyType": "SecondaryMarketAdvisor",

        "overwriteExistingLoan": false,

        "contractUPBLimitIndicator": false,

        "useSellerLoanIdOnly": false,

        "pricingIdentifier": "M99999999",

        "poolNumber": "SA9999"

        }

        ```'
      operationId: importLoanS2S
      parameters:
      - name: env
        in: header
        description: "<p>Environment \n\n </p>"
        required: false
        style: simple
        explode: false
        schema:
          type: string
          default: ProductionBaseline
          enum:
          - ProductionBaseline
          - Pre-Production
      - name: X-LIS-VENDOR-IDENTIFIER
        in: header
        description: A unique identifier that identifies the vendor.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: X-LIS-VENDOR-NAME
        in: header
        description: The vendor company name that identifies the vendor identifier.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: X-LIS-VENDOR-SOFTWARE
        in: header
        description: The vendor software name utilized to submit the loan through the system.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: X-LIS-VENDOR-SOFTWARE-VERSION
        in: header
        description: The vendor software version name utilized to submit the loan through the system.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - file
              - requestMetadataJson
              type: object
              properties:
                file:
                  type: string
                  format: binary
                requestMetadataJson:
                  $ref: '#/components/schemas/LoanImportRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanImportResponse'
              examples:
                ImportLoanResponse:
                  $ref: '#/components/examples/ImportLoanResponse'
        '400':
          description: "<b>Bad Request</b> \n\n <font size='1' color='black'><b>Error codes & details</b></font> \n\n <B>400.001</B> SellerIdentifier Required \n\n <B>400.002</B> SellerIdentifier Invalid Request Type. \n\n <B>400.003</B> FileIdentifier Required \n\n <B>400.004</B> FileIdentifier Invalid Request Type.   \n\n <B>400.005</B> SellerOrganizationBranchIdentifier Required \n\n <B>400.006</B> CorrelationIdentifier Required \n\n <B>400.007</B> CorrelationIdentifier Invalid Data Type. \n\n <B>400.008</B> PoolNumber Invalid Request Type. \n\n <B>400.009</B> Invalid PoolNumber Response\n\n <B>400.010</B> ContractUPBLimitIndicator Required \n\n "
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanImportFileStatusRequest'
              examples:
                SellerIdentifierRequiredResponse:
                  $ref: '#/components/examples/SellerIdentifierRequiredResponse'
                SellerIdentifierInvalidRequestTypeResponse:
                  $ref: '#/components/examples/SellerIdentifierInvalidRequestTypeResponse'
                FileIdentifierRequiredResponse:
                  $ref: '#/components/examples/FileIdentifierRequiredResponse'
                FileIdentifierInvalidRequestTypeResponse:
                  $ref: '#/components/examples/FileIdentifierInvalidRequestTypeResponse'
                SellerOrganizationBranchIdentifierRequiredResponse:
                  $ref: '#/components/examples/SellerOrganizationBranchIdentifierRequiredResponse'
                CorrelationIdentifierRequiredResponse:
                  $ref: '#/components/examples/CorrelationIdentifierRequiredResponse'
                CorrelationIdentifierInvalidDataTypeResponse:
                  $ref: '#/components/examples/CorrelationIdentifierInvalidDataTypeResponse'
                PoolNumberInvalidRequestTypeResponse:
                  $ref: '#/components/examples/PoolNumberInvalidRequestTypeResponse'
                InvalidPoolNumberResponse:
                  $ref: '#/components/examples/InvalidPoolNumberResponse'
                ContractUPBLimitIndicatorRequiredResponse:
                  $ref: '#/components/examples/ContractUPBLimitIndicatorRequiredResponse'
        '401':
          description: "<b>Unauthorized</b> \n\n <font size='1' color='black'><b>Error codes & details </b></font> \n\n <B>401</B> Rejected by policy"
          content:
            application/json:
              examples:
                ImportErrorResponse401:
                  $ref: '#/components/examples/ImportErrorResponse401'
        '403':
          description: "<b>The user does not have the permission to access the function</b> \n\n <font size='1' color='black'><b>Error codes & details </b></font> \n\n <B>403</B> Rejected by policy"
          content:
            application/json:
              examples:
                ImportErrorResponse403:
                  $ref: '#/components/examples/ImportErrorResponse403'
        '500':
          description: "<p><strong>Internal Server Error</strong></p>\n <p><small><small>Error codes &amp; details</small></small></p> <ul><strong>500:</strong> An application error has occurred. Please call 1-800-FREDDIE to report this problem. </ul>"
          content:
            application/json:
              examples:
                FileImportStatusInternalErrorResponse:
                  $ref: '#/components/examples/FileImportStatusInternalErrorResponse'
  /v1/loans/import-status:
    post:
      tags:
      - Loan Import API
      summary: Loan Import File Status API
      operationId: importLoanS2SStatus
      parameters:
      - name: env
        in: header
        description: "<p>Environment \n\n </p>"
        required: false
        style: simple
        explode: false
        schema:
          type: string
          default: ProductionBaseline
          enum:
          - ProductionBaseline
          - Pre-Production
      - name: X-LIS-VENDOR-IDENTIFIER
        in: header
        description: A unique identifier that identifies the vendor.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: X-LIS-VENDOR-NAME
        in: header
        description: The vendor company name that identifies the vendor identifier.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: X-LIS-VENDOR-SOFTWARE
        in: header
        description: The vendor software name utilized to submit the loan through the system.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: X-LIS-VENDOR-SOFTWARE-VERSION
        in: header
        description: The vendor software version name utilized to submit the loan through the system.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanImportFileStatusRequest'
            examples:
              LoanImportFileStatusRequestForSeller:
                $ref: '#/components/examples/LoanImportFileStatusRequestForSeller'
              LoanImportFileStatusRequestForSMA:
                $ref: '#/components/examples/LoanImportFileStatusRequestForSMA'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanImportFileStatusResponse'
              examples:
                LoanImportFileStatusReponseWithoutErrors:
                  $ref: '#/components/examples/LoanImportFileStatusReponseWithoutErrors'
                LoanImportFileStatusIntermediateResponse:
                  $ref: '#/components/examples/LoanImportFileStatusIntermediateResponse'
                LoanImportFileStatusReponseWithErrors:
                  $ref: '#/components/examples/LoanImportFileStatusReponseWithErrors'
        '400':
          description: "<b>Bad Request</b> \n\n <font size='1' color='black'><b>Error codes & details</b></font> \n\n <B>400.001</B> SellerIdentifier Required \n\n <B>400.002</B> SellerIdentifier Invalid Request Type. \n\n<B>400.003</B> FileIdentifier Required \n\n <B>400.004</B> FileIdentifier Invalid Request Type.  \n\n <B>400.005</B>  SellerOrganizationBranchIdentifier Required \n\n <B>400.006</B>  CorrelationIdentifier Required \n\n <B>400.007</B>  CorrelationIdentifier Invalid Data Type. \n\n"
          content:
            application/json:
              examples:
                SellerIdentifierRequiredResponse:
                  $ref: '#/components/examples/SellerIdentifierRequiredResponse'
                SellerIdentifierInvalidRequestTypeResponse:
                  $ref: '#/components/examples/SellerIdentifierInvalidRequestTypeResponse'
                FileIdentifierRequiredResponse:
                  $ref: '#/components/examples/FileIdentifierRequiredResponse'
                FileIdentifierInvalidRequestTypeResponse:
                  $ref: '#/components/examples/FileIdentifierInvalidRequestTypeResponse'
                SellerOrganizationBranchIdentifierRequiredResponse:
                  $ref: '#/components/examples/SellerOrganizationBranchIdentifierRequiredResponse'
                CorrelationIdentifierRequiredResponse:
                  $ref: '#/components/examples/CorrelationIdentifierRequiredResponse'
                CorrelationIdentifierInvalidDataTypeResponse:
                  $ref: '#/components/examples/CorrelationIdentifierInvalidDataTypeResponse'
        '401':
          description: "<b>Unauthorized</b> \n\n <font size='1' color='black'><b>Error codes & details </b></font> \n\n <B>401</B> Rejected by policy"
          content:
            application/json:
              examples:
                ImportErrorResponse401:
                  $ref: '#/components/examples/ImportErrorResponse401'
        '403':
          description: "<b>The user does not have the permission to access the function</b> \n\n <font size='1' color='black'><b>Error codes & details </b></font> \n\n <B>403</B> Rejected by policy"
          content:
            application/json:
              examples:
                ImportErrorResponse403:
                  $ref: '#/components/examples/ImportErrorResponse403'
        '500':
          description: "<p><strong>Internal Server Error</strong></p>\n <p><small><small>Error codes &amp; details</small></small></p> <ul><strong>500:</strong> An application error has occurred. Please call 1-800-FREDDIE to report this problem. </ul>"
          content:
            application/json:
              examples:
                FileImportStatusInternalErrorResponse:
                  $ref: '#/components/examples/FileImportStatusInternalErrorResponse'
components:
  examples:
    FileImportStatusInternalErrorResponse:
      summary: Internal Server error
      value:
        responseDetails:
          fileStatus: Error
          errors:
          - errorCode: SYST0001
            errorMessage: An application error has occurred. Please call 1-800-FREDDIE to report this problem.
            errorType: ImportError
    InvalidPoolNumberResponse:
      value:
        responseDetails:
          fileStatus: Error
          errors:
          - errorCode: LI0012
            errorMessage: The Pool Number provided is not valid.
            errorType: ImportError
    CorrelationIdentifierInvalidDataTypeResponse:
      summary: CorrelationIdentifier Invalid Data Type
      description: The Server can not process the request
      value:
        fileStatus: Error
        errors:
        - errorCode: LIS0002
          errorMessage: 'CorrelationIdentifier: expected type: String, found: Integer.'
    LoanImportFileStatusRequestForSMA:
      value:
        correlationIdentifier: '9999'
        sellerIdentifier: '999999'
        sellerOrganizationBranchIdentifier: 999999
        requestingPartyAccountIdentifier: SMA999
        counterPartyType: SecondaryMarketAdvisor
        fileIdentifier: 99999
    ContractUPBLimitIndicatorRequiredResponse:
      value:
        responseDetails:
          fileStatus: Error
          errors:
          - errorCode: LIS0001
            errorMessage: Required key [contractUPBLimitIndicator] not found.
    LoanImportFileStatusReponseWithoutErrors:
      value:
        fileStatusResultsResponse:
        - fileIdentifier: 99999
          userIdentifier: FREDDIE_ALLROLE10
          fileName: SampleH49Loan_1Loan_2025-09-19 104007_000152_147357.xml
          fileStatus: Completed
          fileCreationTime: 2025-09-19 10:40 AM
          sellerIdentifier: '999999'
          organizationBranchIdentifier: 999999
          totalLoans: 1
          totalLoansProcessed: 1
          totalCurrentUPB: 268000
          totalLoansWithErrors: 0
          totalLoansWithProductErrors: 0
          totalLoansWithProductLabelled: 1
          totalLoansWithImportWarnings: 0
          totalLoansWithProductAndImportWarnings: 0
          totalLoansWithEvaluationErrors: 0
          totalLoansWithEvaluationWarnings: 0
          totalLoansNotEligibleForRNWAssetRelief: 1
          totalLoansNotEligibleForRNWCollateralRelief: 1
          totalLoansNotEligibleForRNWIncomeRelief: 1
          totalLoansWithAllocationErrors: 0
          totalLoansAllocated: 0
          requestToEvaluateLoans: true
    FileIdentifierInvalidRequestTypeResponse:
      summary: FileIdentifier Invalid Request Type
      description: The Server can not process the request
      value:
        fileStatus: Error
        errors:
        - errorCode: LIS0002
          errorMessage: 'FileIdentifier: expected type: Number, found: String.'
    SellerIdentifierInvalidRequestTypeResponse:
      summary: SellerIdentifier Invalid Request Type
      description: The Server can not process the request
      value:
        fileStatus: Error
        errors:
        - errorCode: LIS0002
          errorMessage: 'SellerIdentifier: expected type: String, found: Integer.'
    LoanImportFileStatusRequestForSeller:
      value:
        correlationIdentifier: '9999'
        sellerIdentifier: '999999'
        sellerOrganizationBranchIdentifier: 999999
        counterPartyType: Seller
        fileIdentifier: 99999
    PoolNumberInvalidRequestTypeResponse:
      value:
        responseDetails:
          fileStatus: Error
          errors:
          - errorCode: LIS0002
            errorMessage: 'PoolNumber: expected type: String, found: Integer.'
    SellerOrganizationBranchIdentifierRequiredResponse:
      summary: SellerOrganizationBranchIdentifier Required
      description: The Server can not process the request
      value:
        fileStatus: Error
        errors:
        - errorCode: LIS0001
          errorMessage: Required key [sellerOrganizationBranchIdentifier] not found.
    ImportLoanResponse:
      summary: ImportResponse
      description: The Import loan file status results details
      value:
        responseDetails:
          fileStatus: InProgress
          fileIdentifier: 99999
          sellerIdentifier: '999999'
          fileName: SampleH49Loan_1Loan_2025-09-22 134708_000278_147357.xml
          estimatedTimeToRetrieveImportResultsInSecs: 15
    ImportErrorResponse401:
      value:
        error:
          type: string
          reqruire: true
          example: Rejected by policy
        code:
          type: number
          reqruire: true
          example: 401.007
        errors:
          type: array
          reqruire: true
          example:
          - status: Unauthorized
            detail:
            - error: Invalid User Credentials.
            timestamp: '2021-12-01T19:19:39.906Z'
          items:
            anyOf:
            - type: object
              example:
                status: Unauthorized
                detail:
                - error: Invalid User Credentials.
                timestamp: '2025-07-11T19:19:39.906Z'
              required:
              - status
              - detail
              - timestamp
              properties:
                status:
                  type: string
                  example: Unauthorized
                detail:
                  type: array
                  example:
                  - error: Invalid User Credentials.
                  items:
                    anyOf:
                    - type: object
                      example:
                        error: Invalid User Credentials.
                      required:
                      - error
                      properties:
                        error:
                          type: string
                          example: Invalid User Credentials.
                      additionalProperties: true
                timestamp:
                  type: string
                  example: '2025-07-11T19:19:39.906Z'
              additionalProperties: true
    ImportErrorResponse403:
      value:
        code:
          type: string
          reqruire: true
          example: '403'
        message:
          type: string
          reqruire: true
          example: Access Forbidden
        details:
          type: string
          reqruire: true
          example: Accessing the resource you were trying to reach is forbidden
    LoanImportFileStatusReponseWithErrors:
      value:
        fileStatusResultsResponse:
        - fileIdentifier: 99999
          userIdentifier: test_pmasys2sys76
          fileName: Loan_Cash_Retained_SIT44_New_2025-06-24 112158_000250_147357.xml
          fileStatus: Error
          fileCreationTime: 2025-06-24 11:21 AM
          sellerIdentifier: '999999'
          organizationBranchIdentifier: 999999
          totalLoans: 2
          totalLoansProcessed: 2
          totalCurrentUPB: 489000
          totalLoansWithErrors: 1
          totalCurrentUPBOfLoansWithImportErrors: 244500
          totalLoansWithProductErrors: 1
          totalCurrentUPBOfLoansWithProductErrors: 244500
          totalLoansWithProductLabelled: 1
          totalLoansWithImportWarnings: 1
          totalCurrentUPBOfLoansWithImportWarnings: 244500
          totalLoansWithProductAndImportWarnings: 1
          totalLoansWithEvaluationErrors: 1
          totalCurrentUPBOfLoansWithCriticalErrors: 244500
          totalLoansWithEvaluationWarnings: 1
          totalLoansWithoutEvaluationWarnings: 0
          totalLoansNotEligibleForRNWAssetRelief: 1
          totalLoansNotEligibleForRNWCollateralRelief: 1
          totalLoansNotEligibleForRNWIncomeRelief: 0
          totalLoansWithAllocationErrors: 1
          totalCurrentUPBOfLoansWithAllocationErrors: 244500
          totalLoansAllocated: 0
          requestToEvaluateLoans: true
          errorDetails:
          - sellerLoanIdentifier: TEST_SM37_0204
            investorContractIdentifier: 99999999
            freddieMacLoanIdentifier: '999999999'
            primaryBorrowerIndividualFullName: HAN2, PHIL2
            loanIdentifier: 999999999
            errors:
            - errorCode: LAE9002
              errorMessage: Loan could not be allocated at this time.
              errorType: AllocationError
            - errorCode: LIW0005
              errorMessage: Based upon the attributes provided, Loan Reference Product Label cannot be determined.
              errorType: ProductError
            - errorCode: LIW0002
              errorMessage: Loan has already been added to a Form 1034E, and the Document Custodian and the Servicer Identifiers from the Form 1034E remain on the loan.
              errorType: ImportWarning
            - errorCode: PD4004
              errorMessage: Combined LTV Ratio Percent must match the Freddie Mac calculated Combined LTV Ratio Percent.
              errorType: EvaluationError
              criticalityType: Error
              complianceType: DataReasonableness
            - errorCode: PF9900
              errorMessage: Standardized Property Address - Seller Delivered should match Standardized Property Address - UCDP.
              errorType: EvaluationError
              criticalityType: Warning
              complianceType: AppraisalEligibility
            - errorCode: CY1010
              errorMessage: Loan is eligible for collateral representation and warranty relief with an appraisal waiver. Seller is relieved of representations and warranties related to value, condition and marketability.
              errorType: RepresentationAndWarrantyReliefError
              complianceType: Collateral
            - errorCode: IY1000
              errorMessage: This loan has been granted income representation and warranty relief.
              errorType: RepresentationAndWarrantyReliefError
              complianceType: Income
            - errorCode: AZ2105
              errorMessage: Mortgages with Closing Cost Funds Type of Gift Funds are not eligible for asset representation and warranty relief.
              errorType: RepresentationAndWarrantyReliefError
              complianceType: Asset
          - sellerLoanIdentifier: TEST_ARM_LOAN_ERROR
            primaryBorrowerIndividualFullName: AMERICA, ANDY
            errors:
            - errorCode: LI0093
              errorMessage: Note Amount must be provided for the Latest Loan State Type.
              errorType: ImportError
            - errorCode: LI0074
              errorMessage: Automated Underwriting Case Identifier AUWCI_Test_unique_1 with the Automated Underwriting System Type of Loan Product Advisor already exists and cannot be added to this loan.
              errorType: ImportError
    SellerIdentifierRequiredResponse:
      summary: SellerIdentifier Required
      value:
        fileStatus: Error
        errors:
        - errorCode: LIS0001
          errorMessage: Required key [sellerIdentifier] not found.
    FileIdentifierRequiredResponse:
      summary: FileIdentifier Required
      description: The Server can not process the request
      value:
        fileStatus: Error
        errors:
        - errorCode: LIS0001
          errorMessage: Required key [fileIdentifier] not found.
    LoanImportFileStatusIntermediateResponse:
      value:
        fileStatusResultsResponse:
        - fileIdentifier: 99999
          userIdentifier: test_pmasys2sys76
          fileName: Loan_Cash_Retained_SIT44_New_2025-06-24 112158_000250_147357.xml
          fileStatus: Error
          fileCreationTime: 2025-06-24 11:21 AM
          sellerIdentifier: '999999'
          organizationBranchIdentifier: 999999
          totalLoans: 2
          totalCurrentUPB: 489000
          totalLoansWithErrors: 1
          totalCurrentUPBOfLoansWithImportErrors: 244500
          totalLoansWithProductErrors: 1
          totalCurrentUPBOfLoansWithProductErrors: 244500
          totalLoansWithProductLabelled: 1
          totalLoansWithImportWarnings: 1
          totalCurrentUPBOfLoansWithImportWarnings: 244500
          totalLoansWithProductAndImportWarnings: 1
          totalLoansWithEvaluationErrors: 1
          totalCurrentUPBOfLoansWithCriticalErrors: 244500
          totalLoansWithEvaluationWarnings: 1
          totalLoansWithoutEvaluationWarnings: 0
          totalLoansNotEligibleForRNWAssetRelief: 1
          totalLoansNotEligibleForRNWCollateralRelief: 1
          totalLoansNotEligibleForRNWIncomeRelief: 0
          totalLoansWithAllocationErrors: 1
          totalCurrentUPBOfLoansWithAllocationErrors: 244500
          totalLoansAllocated: 0
          requestToEvaluateLoans: true
    CorrelationIdentifierRequiredResponse:
      summary: CorrelationIdentifier Required
      description: The Server can not process the request
      value:
        fileStatus: Error
        errors:
        - errorCode: LIS0001
          errorMessage: Required key [correlationIdentifier] not found.
  schemas:
    LoanImportRequest:
      description: This is the metadata for Loan Import processing.
      required:
      - correlationIdentifier
      - sellerIdentifier
      - sellerOrganizationBranchIdentifier
      - counterPartyType
      - overwriteExistingLoan
      - contractUPBLimitIndicator
      - useSellerLoanIdOnly
      type: object
      properties:
        correlationIdentifier:
          type: string
          description: The unique identifier that is provided by the Seller or Secondary Market Advisor for each request.
          example: '9999'
        sellerIdentifier:
          maxLength: 6
          type: string
          description: The unique identifier assigned to a party, which may be an individual, a counterparty, or a related organization.
          example: '999999'
        sellerOrganizationBranchIdentifier:
          type: integer
          description: The unique identifier assigned for an organization unit.
          example: 999999
        requestingPartyAccountIdentifier:
          type: string
          description: The unique identifier assigned to a party, which may be an individual or a counterparty.
          example: SMA999
        counterPartyType:
          type: string
          description: A discrete set of values that specifies the different roles that a counterparty will perform in relationship with Freddie Mac.
          example: SecondaryMarketAdvisor
        overwriteExistingLoan:
          type: boolean
          description: Indicator to allow loans to be overwritten during modification.
          example: true
        contractUPBLimitIndicator:
          type: boolean
          description: Indicator to provide an error message when the total Unpaid Principal Balance Amount of the loans being allocated to a Cash Contract exceeds the Contract Amount.
          example: false
        useSellerLoanIdOnly:
          type: boolean
          description: Indicator to use seller loan identifier as the loan identifier to determine loan's uniqueness during creation or modification of a loan.
          example: false
        requestToEvaluateLoans:
          description: Indicator to request to evaluate loans during creation or modification of a loan.
          type: boolean
          example: false
        pricingIdentifier:
          type: string
          description: A unique identification assigned to an entity (e.g., Seller, Seller Family) or contracting vehicle (e.g., MA, MC).
          example: M99999999
        investorContractIdentifier:
          type: integer
          description: A unique identifier for a group of loans identified as part of a cash pool or a security pool.
          example: 99999999
        poolNumber:
          type: string
          description: The unique designation assigned to the security by the issuer.
          example: SA9999
    LoanImportResponse:
      description: The Import loan file status results details.
      required:
      - estimatedTimeToRetrieveImportResultsInSecs
      - fileIdentifier
      - fileName
      - fileStatus
      - sellerIdentifier
      type: object
      properties:
        responseDetails:
          type: object
          properties:
            fileStatus:
              maxLength: 30
              type: string
              description: The status of the import loan file.
              example: InProgress
            fileIdentifier:
              type: integer
              description: The file identifier for the import loan file.
              example: 38587
            sellerIdentifier:
              maxLength: 6
              type: string
              description: The unique identifier assigned to a party, which may be an individual, a counterparty, or a related organization.
              example: '999999'
            fileName:
              maxLength: 130
              type: string
              description: The name of the import loan file.
              example: 3H49Loans_ImpErr_ProdErr_ImpWrng 3Loans.xml
            estimatedTimeToRetrieveImportResultsInSecs:
              type: integer
              description: The estimated time, in seconds, to retrieve the import results.
              example: 15
            errors:
              type: array
              items:
                properties:
                  errorCode:
                    type: string
                    description: A unique code value associated with the error message.
                    example: LI0019
                  errorMessage:
                    type: string
                    description: The error message corresponding to the error code sent.
                    example: The value entered for the Financed Unit Count is not a valid value. Please correct the value to a number between 1 and 4 and resubmit the loan.
                  errorType:
                    type: string
                    description: The type of error triggered such as Import, Product, Allocation, Evaluation and Representation and Warranty Relief.
                    example: ImportError
    LoanImportFileStatusResponse:
      description: The Import loan file status results details.
      required:
      - fileCreationTime
      - fileIdentifier
      - fileName
      - fileStatus
      - organizationBranchIdentifier
      - requestToEvaluateLoans
      - sellerIdentifier
      - totalCurrentUPB
      - totalLoans
      - totalLoansProcessed
      - userIdentifier
      type: object
      properties:
        fileStatusResultsResponse:
          type: array
          items:
            properties:
              fileIdentifier:
                description: The file identifier for the import loan file.
                type: integer
                format: int64
                example: 99999
              userIdentifier:
                description: The unique identifier assigned for a user.
                type: string
                example: FREDDIE_ALLROLE10
              fileName:
                description: The name of the import loan file.
                maxLength: 130
                type: string
                example: Loan_Cash_Retained_SIT44_New_2025-06-24 112158_000250_147357.xml
              fileStatus:
                description: The status of the import loan file.
                type: string
                maxLength: 30
                example: InProgress, Error, Completed
              fileCreationTime:
                description: The date and time the import loan file was imported.
                type: string
                example: 2025-09-19 10:40 AM
              sellerIdentifier:
                description: The unique identifier assigned to a party, which may be an individual, a counterparty, or a related organization.
                maxLength: 6
                type: string
                example: '999999'
              organizationBranchIdentifier:
                description: The unique identifier assigned for an organization unit.
                type: integer
                format: int64
                example: 999999
              totalLoans:
                description: The total count of loans identified in the import loan file.
                type: integer
                format: int32
                example: 2
              totalLoansProcessed:
                description: The total count of loans that were successfully processed.
                type: integer
                format: int32
                example: 2
              totalCurrentUPB:
                description: The total Current UPB of loans that were successfully created and/or modified.
                type: number
                format: double
                example: 489000
              totalLoansWithErrors:
                description: The total count of loans that have import errors.
                type: integer
                format: int32
                example: 1
              totalCurrentUPBOfLoansWithImportErrors:
                description: The total Current UPB of loans that have import errors.
                type: number
                format: double
                example: 244500
              totalCurrentUPBOfLoansWithProductErrors:
                description: The total Current UPB of loans that have product errors.
                type: number
                format: double
                example: 244500
              totalCurrentUPBOfLoansWithImportWarnings:
                description: The total Current UPB of loans that have import warnings.
                type: number
                format: double
                example: 244500
              totalLoansWithProductErrors:
                description: The total count of loans that have product errors.
                type: integer
                format: int32
                example: 1
              totalLoansWithProductLabelled:
                description: The total count of loans that were successfully labeled to a Loan Reference Product Label.
                type: integer
                format: int32
                example: 1
              totalLoansWithImportWarnings:
                description: The total count of loans that have import warnings.
                type: integer
                format: int32
                example: 1
              totalLoansWithProductAndImportWarnings:
                description: The total count of loans that have both product errors and import warnings.
                type: integer
                format: int32
                example: 1
              totalLoansWithEvaluationErrors:
                description: The total count of loans that have critical evaluation errors.
                type: integer
                format: int32
                example: 1
              totalLoansWithEvaluationWarnings:
                description: The total count of loans imported that have evaluation warnings.
                type: integer
                format: int32
                example: 1
              totalLoansNotEligibleForRNWAssetRelief:
                description: The total count of loans imported that are not eligible for Representation and Warranty Asset Relief.
                type: integer
                format: int32
                example: 1
              totalLoansNotEligibleForRNWCollateralRelief:
                description: The total count of loans imported that are not eligible for Representation and Warranty Collateral Relief.
                type: integer
                format: int32
                example: 1
              totalLoansNotEligibleForRNWIncomeRelief:
                description: The total count of loans imported that are not eligible for Representation and Warranty Income Relief.
                type: integer
                format: int32
                example: 1
              requestToEvaluateLoans:
                description: Indicator to request to evaluate loans during creation or modification of a loan.
                type: boolean
                example: true
              totalLoansWithAllocationErrors:
                description: The total count of loans imported that have allocation errors.
                type: integer
                format: int32
                example: 1
              totalLoansAllocated:
                description: The total count of loans imported that were successfully allocated to a contract or pool number.
                type: integer
                format: int32
                example: 1
              totalCurrentUPBOfLoansWithAllocationErrors:
                description: The total Current UPB of loans imported that have allocation errors.
                type: number
                format: double
                example: 244500
              errorDetails:
                type: array
                items:
                  properties:
                    sellerLoanIdentifier:
                      description: A unique identifier assigned by the seller to the loan.
                      type: string
                      example: TEST_ARM_PROD_ERROR
                    investorContractIdentifier:
                      description: A unique identifier for a group of loans identified as part of a cash pool or a security pool.
                      type: integer
                      format: int32
                      example: 999999999
                    freddieMacLoanIdentifier:
                      description: A Freddie Mac supplied number assigned to the Mortgage by the Seller/Servicer.
                      type: string
                      example: '999999999'
                    primaryBorrowerIndividualFullName:
                      description: The unparsed name of either an individual or a legal entity.
                      type: string
                      example: AMERICA, ANDY
                    loanIdentifier:
                      description: The unique identifier assigned to a mortgage loan.
                      type: integer
                      format: int64
                      example: 999999999
                    errors:
                      type: array
                      items:
                        properties:
                          errorCode:
                            description: A unique code value associated with the error message.
                            type: string
                            example: LI0019
                          errorMessage:
                            description: The error message corresponding to the error code sent.
                            type: string
                            example: The value entered for the Financed Unit Count is not a valid value. Please correct the value to a number between 1 and 4 and resubmit the loan.
                          errorType:
                            description: The type of error triggered such as Import, Product, Allocation, Evaluation and Representation and Warranty Relief.
                            type: string
                            example: ImportError, AllocationError, ProductError, EvaluationError, InternalError, ImportWarning, RepresentationAndWarrantyReliefError
                          criticalityType:
                            description: The level of criticality for the error returned when the loan is evaluated.
                            type: string
                            example: Warning, Error
                          complianceType:
                            description: The compliance type for the evaluation error or warning returned when the loan is evaluated.
                            type: string
                            example: Collateral, DataReasonableness, AppraisalEligibility, Collateral, Income, Asset
    LoanImportFileStatusRequest:
      description: This is the request metadata for Loan Import Status processing.
      required:
      - correlationIdentifier
      - sellerIdentifier
      - sellerOrganizationBranchIdentifier
      - counterPartyType
      - fileIdentifier
      type: object
      properties:
        correlationIdentifier:
          type: string
          description: The unique identifier that is provided by the Seller or Secondary Market Advisor for each request.
          example: '9999'
        sellerIdentifier:
          maxLength: 6
          type: string
          description: The unique identifier assigned to a party,  which may be an individual, a counterparty, or a related organization.
          example: '999999'
        sellerOrganizationBranchIdentifier:
          type: integer
          description: The unique identifier assigned for an organization unit.
          example: 999999
        requestingPartyAccountIdentifier:
          type: string
          description: The unique identifier assigned to a party, which may be an individual or a counterparty.
          example: SMA999
        counterPartyType:
          type: string
          description: A discrete set of values that specifies the different roles that a counterparty will perform in relationship with Freddie Mac.
          example: Seller
        fileIdentifier:
          type: integer
          description: The file identifier for the import loan file.
          example: 9999
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: token
